# Generated by Django 4.2.16 on 2025-02-20 20:17

import django.core.validators
from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutme",
            name="text",
            field=mdeditor.fields.MDTextField(
                max_length=500,
                validators=[
                    django.core.validators.MinLengthValidator(10, message="Минимум 10 символов"),
                    django.core.validators.MaxLengthValidator(500, message="Максимум 500 символов"),
                ],
                verbose_name="Текст",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="text",
            field=mdeditor.fields.MDTextField(
                max_length=500,
                validators=[
                    django.core.validators.MinLengthValidator(10, message="Минимум 10 символов"),
                    django.core.validators.MaxLengthValidator(500, message="Максимум 500 символов"),
                ],
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="maininf",
            name="text",
            field=mdeditor.fields.MDTextField(
                max_length=500,
                validators=[
                    django.core.validators.MinLengthValidator(10, message="Минимум 10 символов"),
                    django.core.validators.MaxLengthValidator(500, message="Максимум 500 символов"),
                ],
                verbose_name="Текст",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="text",
            field=mdeditor.fields.MDTextField(
                max_length=500,
                validators=[
                    django.core.validators.MinLengthValidator(10, message="Минимум 10 символов"),
                    django.core.validators.MaxLengthValidator(500, message="Максимум 500 символов"),
                ],
                verbose_name="Описание",
            ),
        ),
    ]
