# Generated by Django 4.2.16 on 2025-02-13 06:51

import blog.utils
import blog.validators.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_draft",
                    models.BooleanField(
                        choices=[(True, "Черновик"), (False, "Опубликовано")],
                        default=0,
                        verbose_name="Черновик",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                5, message="Минимум 5 символов"
                            )
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, message="Минимум 1 символ"
                            ),
                            django.core.validators.RegexValidator(
                                message="Разрешены только строчные буквы (a-z), цифры (0-9) и дефисы (-).",
                                regex="^[a-z0-9-]+$",
                            ),
                        ],
                        verbose_name="Slug",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=blog.utils.article_image_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "svg"]
                            ),
                            blog.validators.validators.validate_article_image_size,
                        ],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "content",
                    mdeditor.fields.MDTextField(
                        validators=[
                            django.core.validators.MinLengthValidator(1, message="Минимум 1 символ")
                        ],
                        verbose_name="Текст",
                    ),
                ),
                (
                    "published",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации"),
                ),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("views", models.PositiveIntegerField(default=0, verbose_name="Просмотры")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["-published"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_draft",
                    models.BooleanField(
                        choices=[(True, "Черновик"), (False, "Опубликовано")],
                        default=0,
                        verbose_name="Черновик",
                    ),
                ),
                (
                    "cat_name",
                    models.CharField(
                        db_index=True,
                        max_length=30,
                        validators=[
                            django.core.validators.MinLengthValidator(1, message="Минимум 1 символ")
                        ],
                        verbose_name="Категория",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, message="Минимум 1 символ"
                            ),
                            django.core.validators.RegexValidator(
                                message="Разрешены только строчные буквы (a-z), цифры (0-9) и дефисы (-).",
                                regex="^[a-z0-9-]+$",
                            ),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_draft",
                    models.BooleanField(
                        choices=[(True, "Черновик"), (False, "Опубликовано")],
                        default=0,
                        verbose_name="Черновик",
                    ),
                ),
                (
                    "tag_name",
                    models.CharField(
                        db_index=True,
                        max_length=30,
                        validators=[
                            django.core.validators.MinLengthValidator(1, message="Минимум 1 символ")
                        ],
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, message="Минимум 1 символ"
                            ),
                            django.core.validators.RegexValidator(
                                message="Разрешены только строчные буквы (a-z), цифры (0-9) и дефисы (-).",
                                regex="^[a-z0-9-]+$",
                            ),
                        ],
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=blog.utils.tag_icon_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["svg", "png"]
                            ),
                            blog.validators.validators.validate_tag_icon_size,
                        ],
                        verbose_name="Иконка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "html_content",
                    models.TextField(
                        max_length=500,
                        validators=[
                            django.core.validators.MinLengthValidator(1, message="Минимум 1 символ")
                        ],
                        verbose_name="Текст",
                    ),
                ),
                (
                    "date_publication",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="blog.article",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="replies",
                        to="blog.comment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["date_publication"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="blog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                related_name="articles", to="blog.tag", verbose_name="Теги"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["-published"], name="blog_articl_publish_f03bae_idx"),
        ),
    ]
