# Generated by Django 4.2.16 on 2025-02-15 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(
                default="#838DD1",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите цвет в HEX-формате, кроме белого (#FFFFFF). Близкие к белому оттенки не рекомендуются.",
                        regex="^(?!#ffffff|#FFFFFF)(#(?:[0-9a-fA-F]{3}){1,2})$",
                    )
                ],
            ),
        ),
    ]
