# Generated by Django 4.2.16 on 2025-01-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
        ),
    ]
