# Generated by Django 4.2.16 on 2025-02-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='Category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
