# Generated by Django 4.2.16 on 2025-02-09 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_publication",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 9, 23, 2, 36, 479395, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата публикации",
            ),
        ),
    ]
