# Generated by Django 4.2.16 on 2025-01-09 09:17

import blog.utils
import blog.validators.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=blog.utils.tag_icon_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg", "png"]
                    ),
                    blog.validators.validators.validate_tag_icon_size,
                ],
                verbose_name="Иконка",
            ),
        ),
    ]
