# Generated by Django 4.2.16 on 2025-02-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article_tags_articletag_article_tags_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="tags",
        ),
    ]
