# Generated by Django 4.2.16 on 2025-02-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_article_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="tags_new",
            new_name="tags",
        ),
    ]
