# Generated by Django 4.2.16 on 2025-02-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_comment_date_publication"),
        ("blog", "0005_rename_tags_new_article_tags"),
    ]

    operations = []
